import type { LocalizedExperience, LocalizedText } from "../types"

// Side projects du CV, affichés après les expériences de leur page.
// Même structure et même rendu qu'une expérience professionnelle.
// - `page` (1 ou 2) : déplacer un projet d'une page à l'autre pour rééquilibrer.
// - Dans les textes, les segments entre ** sont rendus en gras violet.
// - Les deux langues s'écrivent côte à côte (fr/en), ou en une fois via
//   bothLanguages quand le texte est identique — voir LocalizedText dans ../types.ts.
// - Une mission peut être taguée `tag: [...]` (ex. `tag: ["hybrid", "pm"]`)
//   pour remonter en tête (ou redescendre en fin) de sa liste quand une des
//   accroches listées est choisie. Elle peut aussi être réservée à un
//   sous-ensemble d'accroches avec `only: [...]` (ex. `only: ["hybrid", "pm"]`) :
//   elle n'apparaît alors que pour les accroches listées — voir
//   PitchTaggedText dans ../types.ts.
// - Un side project entier peut être marqué `hiddenFor: ["pm"]` (ou toute
//   autre accroche) pour être masqué entièrement — voir resolveSideProjects
//   dans ../buildLocale.ts.

/** Titre de la section. */
export const SIDE_PROJECTS_TITLE: LocalizedText = {
  bothLanguages: "Side projects",
}

export const SIDE_PROJECTS: LocalizedExperience[] = [
  {
    page: 2,
    role: { bothLanguages: "Calendor" },
    employer: {
      fr: "Projet personnel (2026 - aujourd'hui)",
      en: "Personal solo project (2026 - present)",
    },
    hiddenFor: ["pm"],
    context: [
      {
        fr: "Application web qui génère des documents PDF personnalisés.",
        en: "Web app generating personalized PDF documents.",
      },
    ],
    missions: [
      {
        tag: ["hybrid"],
        fr: "Pilotage du projet en autonomie complète : cadrage du besoin, priorisation des fonctionnalités, arbitrages scope/délai, de l'idée à la mise en production",
        en: "End-to-end project ownership in full autonomy: scoping requirements, prioritizing features, scope/timeline trade-offs, from idea to production",
      },
      {
        fr: "**Authentification** et **base de données** (Subapase)",
        en: "**Authentication** and **database** (Supabase)",
      },
      {
        fr: "Qualité : TypeScript, Biome + oxlint, accessibilité **WCAG AAA**",
        en: "Quality: TypeScript, Biome + oxlint, **WCAG AAA** accessibility",
      },
      {
        fr: "Développement **assisté par IA** : règles d'agents centralisées (AGENTS.md), relecture systématique, adaptation du modèle à la tâche",
        en: "**AI-assisted development**: centralized agent rules (AGENTS.md), systematic review, model adaptation to the task",
      },
      {
        tag: ["hybrid", "pm"],
        fr: "Définition de la roadmap",
        en: "Roadmap definition",
      },
      {
        tag: ["hybrid"],
        fr: "Conception des fonctionnalités, de l'UX/UI, et des documents générés",
        en: "Designing features, UX/UI, and the generated documents",
      },
      {
        fr: "**Ce CV a été généré par Calendor.**",
        en: "**This resume was generated by Calendor.**",
      },
    ],
    stack: [
      { bothLanguages: "React 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "Vite" },
      { bothLanguages: "@react-pdf/renderer" },
      { bothLanguages: "Supabase" },
      { bothLanguages: "Biome" },
      { bothLanguages: "oxlint" },
      { bothLanguages: "GitHub Pages" },
      { bothLanguages: "Claude Code" },
    ],
  },
  {
    page: 2,
    role: { bothLanguages: "Resume" },
    employer: {
      fr: "Projet personnel (2025 - aujourd'hui)",
      en: "Personal solo project (2025 - present)",
    },
    hiddenFor: ["pm"],
    context: [
      {
        fr: "CV en ligne développé en Angular.",
        en: "Online resume built with Angular.",
      },
    ],
    missions: [
      {
        fr: "Site **Angular 19** avec rendu côté serveur (**SSR**)",
        en: "**Angular 19** website with server-side rendering (**SSR**)",
      },
      {
        fr: "**Internationalisation** français / anglais (@angular/localize)",
        en: "French / English **internationalization** (@angular/localize)",
      },
      {
        fr: "Définition du design, de l'UX/UI, de l'architecture, de la structure du contenu",
        en: "Design, UX/UI, architecture, and content structure definition",
      },
      {
        only: ["dev"],
        fr: "Composants **PrimeNG**",
        en: "**PrimeNG** components",
      },
      {
        only: ["dev"],
        fr: "Tests unitaires **Jasmine / Karma**",
        en: "**Jasmine / Karma** unit tests",
      },
    ],
    stack: [
      { bothLanguages: "Angular 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "SSR" },
      { bothLanguages: "PrimeNG" },
      { bothLanguages: "RxJS" },
      { bothLanguages: "Jasmine" },
      { bothLanguages: "Karma" },
      { bothLanguages: "Prettier" },
    ],
  },
]
