import type { LocalizedExperience, LocalizedText } from "../types"

// Side projects du CV, affichés après les expériences de leur page.
// Même structure et même rendu qu'une expérience professionnelle.
// - `page` (1 ou 2) : déplacer un projet d'une page à l'autre pour rééquilibrer.
// - Dans les textes, les segments entre ** sont rendus en gras violet.
// - Les deux langues s'écrivent côte à côte (fr/en), ou en une fois via
//   bothLanguages quand le texte est identique — voir LocalizedText dans ../types.ts.
// - Une mission peut être taguée `tag: "pm"` ou `tag: "dev"` pour remonter en
//   tête (ou redescendre en fin) de sa liste selon l'accroche choisie. Elle
//   peut aussi être réservée à une accroche avec `only: "pm"` ou
//   `only: "dev"` : elle n'apparaît alors que pour cette accroche — voir
//   PitchTaggedText dans ../types.ts.

/** Titre de la section. */
export const SIDE_PROJECTS_TITLE: LocalizedText = {
  bothLanguages: "Side projects",
}

export const SIDE_PROJECTS: LocalizedExperience[] = [
  {
    page: 2,
    role: { bothLanguages: "Calendor" },
    employer: {
      fr: "Projet personnel (2026 - aujourd'hui)",
      en: "Personal solo project (2026 - present)",
    },
    context: [
      {
        fr: "Application web qui génère des documents PDF personnalisés : calendriers, CV multilangues etc.",
        en: "Web app generating personalized PDF documents: calendars, multilingual resumes, etc.",
      },
    ],
    missions: [
      {
        fr: "Génération des PDF 100% côté client (@react-pdf/renderer) : documents paramétrables (contenu, design, mise en page)",
        en: "Client-side PDF generation (@react-pdf/renderer): documents are fully customizable (content, design, layout)",
      },
      {
        tag: "pm",
        fr: "Pilotage du projet en autonomie complète : cadrage du besoin, priorisation des fonctionnalités, arbitrages scope/délai, de l'idée à la mise en production",
        en: "End-to-end project ownership in full autonomy: scoping requirements, prioritizing features, scope/timeline trade-offs, from idea to production",
      },
      {
        fr: "**Authentification** et **base de données** (Subapase)",
        en: "**Authentication** and **database** (Supabase)",
      },
      {
        fr: "Qualité : **TypeScript strict**, Biome + oxlint, accessibilité **WCAG AAA**",
        en: "Quality: **strict TypeScript**, Biome + oxlint, **WCAG AAA** accessibility",
      },
      {
        fr: "Développement **assisté par IA** : règles d'agents centralisées (AGENTS.md), relecture systématique, adaptation du modèle à la tâche",
        en: "**AI-assisted development**: centralized agent rules (AGENTS.md), systematic review, model adaptation to the task",
      },
      {
        tag: "pm",
        fr: "Roadmap itérative : livraison incrémentale des fonctionnalités ",
        en: "Iterative roadmap: incremental delivery of features",
      },
      {
        tag: "pm",
        fr: "Conception des fonctionnalités, de l'UX/UI, et des documents générés",
        en: "Designing features, UX/UI, and the generated documents",
      },
      {
        fr: "**Ce CV a été généré par Calendor.**",
        en: "**This resume was generated by Calendor.**",
      },
    ],
    stack: [
      { bothLanguages: "React 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "Vite" },
      { bothLanguages: "@react-pdf/renderer" },
      { bothLanguages: "Supabase" },
      { bothLanguages: "Biome" },
      { bothLanguages: "oxlint" },
      { bothLanguages: "GitHub Pages" },
      { bothLanguages: "Claude Code" },
    ],
  },
  {
    page: 2,
    role: { bothLanguages: "Resume" },
    employer: {
      fr: "Projet personnel (2025 - aujourd'hui)",
      en: "Personal solo project (2025 - present)",
    },
    context: [
      {
        fr: "CV en ligne développé en Angular.",
        en: "Online resume built with Angular.",
      },
    ],
    missions: [
      {
        fr: "Site **Angular 19** avec rendu côté serveur (**SSR**)",
        en: "**Angular 19** website with server-side rendering (**SSR**)",
      },
      {
        fr: "**Internationalisation** français / anglais (@angular/localize)",
        en: "French / English **internationalization** (@angular/localize)",
      },
      {
        fr: "Composants **PrimeNG**",
        en: "**PrimeNG** components",
      },
      {
        fr: "Tests unitaires **Jasmine / Karma**",
        en: "**Jasmine / Karma** unit tests",
      },
    ],
    stack: [
      { bothLanguages: "Angular 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "SSR" },
      { bothLanguages: "PrimeNG" },
      { bothLanguages: "RxJS" },
      { bothLanguages: "Jasmine" },
      { bothLanguages: "Karma" },
      { bothLanguages: "Prettier" },
    ],
  },
]
