import type { LocalizedExperience, LocalizedText } from "../types"

// Side projects du CV, affichés après les expériences de leur page.
// Même structure et même rendu qu'une expérience professionnelle.
// - `page` (1 ou 2) : déplacer un projet d'une page à l'autre pour rééquilibrer.
// - Dans les textes, les segments entre ** sont rendus en gras violet.
// - Les deux langues s'écrivent côte à côte (fr/en), ou en une fois via
//   bothLanguages quand le texte est identique — voir LocalizedText dans ../types.ts.

/** Titre de la section. */
export const SIDE_PROJECTS_TITLE: LocalizedText = {
  bothLanguages: "Side projects",
}

export const SIDE_PROJECTS: LocalizedExperience[] = [
  {
    page: 2,
    role: { bothLanguages: "Calendor" },
    employer: {
      fr: "Projet personnel (2026 - aujourd'hui)",
      en: "Personal solo project (2026 - present)",
    },
    context: [
      {
        fr: "Application web qui génère des documents d'organisation au design moderne : calendriers personnalisés, CV multilangues, pages de bullet journal, listes de courses, courriers, menus de batch cooking, etc.",
        en: "Web app generating personalized modern-style organization documents: custom calendars, multilingual resumes, bullet journal pages, grocery lists, letters, batch cooking menus.",
      },
    ],
    missions: [
      {
        fr: "Génération des **PDF 100% côté client** (@react-pdf/renderer) : calendriers multi-pages avec événements récurrents, jours fériés et illustrations, bullet journal paramétrable (colonnes, pointillés, cases à cocher), listes de courses avec presets",
        en: "**100% client-side PDF generation** (@react-pdf/renderer): multi-page calendars with recurring events and tasks, public holidays and life events, configurable bullet journal pages, grocery lists with presets",
      },
      {
        fr: "Définition du besoin, conception des fonctionnalités, de l'UX/UI, et des documents générés",
        en: "Defining requirements, designing features, designing UX/UI, and designingthe generated documents",
      },
      {
        fr: "**Authentification** et **base de données** via Subapase",
        en: "Supabase **authentication** and **database**",
      },
      {
        fr: "Calculs de calendrier en **UTC natif**, sans librairie de dates",
        en: "Calendar computations in **native UTC**, with no date library",
      },
      {
        fr: "Qualité : **TypeScript strict**, Biome + oxlint, accessibilité **WCAG AAA**",
        en: "Quality: **strict TypeScript**, Biome + oxlint, **WCAG AAA** accessibility",
      },
      {
        fr: "Développement **assisté par IA** : règles d'agents centralisées (AGENTS.md), relecture systématique, adaptation du modèle à la tâche",
        en: "**AI-assisted development**: centralized agent rules (AGENTS.md), systematic review, model adaptation to the task",
      },
      {
        fr: "Ce CV a été généré par Calendor.",
        en: "This resume was generated by Calendor",
      },
    ],
    stack: [
      { bothLanguages: "React 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "Vite" },
      { bothLanguages: "@react-pdf/renderer" },
      { bothLanguages: "Supabase" },
      { bothLanguages: "Biome" },
      { bothLanguages: "oxlint" },
      { bothLanguages: "GitHub Pages" },
      { bothLanguages: "Claude Code" },
    ],
  },
  {
    page: 2,
    role: { bothLanguages: "Resume" },
    employer: {
      fr: "Projet personnel (2025 - aujourd'hui)",
      en: "Personal solo project (2025 - present)",
    },
    context: [
      {
        fr: "CV en ligne développé en Angular.",
        en: "Online resume built with Angular.",
      },
    ],
    missions: [
      {
        fr: "Site **Angular 19** avec rendu côté serveur (**SSR**)",
        en: "**Angular 19** website with server-side rendering (**SSR**)",
      },
      {
        fr: "**Internationalisation** français / anglais (@angular/localize)",
        en: "French / English **internationalization** (@angular/localize)",
      },
      {
        fr: "Composants **PrimeNG**",
        en: "**PrimeNG** components",
      },
      {
        fr: "Tests unitaires **Jasmine / Karma**",
        en: "**Jasmine / Karma** unit tests",
      },
    ],
    stack: [
      { bothLanguages: "Angular 19" },
      { bothLanguages: "TypeScript" },
      { bothLanguages: "SSR" },
      { bothLanguages: "PrimeNG" },
      { bothLanguages: "RxJS" },
      { bothLanguages: "Jasmine" },
      { bothLanguages: "Karma" },
      { bothLanguages: "Prettier" },
    ],
  },
]
